### ISSUE TITLE
Disable Check for AD group during sync (?)

### ISSUE THREAD

**Issue by Axel-L** [SnowSoftware/AutomationPlatform-SLM.Integration#1]
Tested on AP 3.6 today:

On the application "Store" tab in SLM, the verification of the AD Group has been disabled lately. 
This is reasonable in environments, where you do not use AD groups as deployment targets (you still need to enter some text into the field and the value has to be unique).

When I now enter any text (e.g. "XYZ") into the "Identifier (AD group)" field in SLM , I will get an error later when importing apps from SLM saying:
"Error adding application: Failed to validate AD group "XYZ": Group "XYZ" not found in Active Directory"
--> line 221 in "import slm applications.ps1"

I obviously can comment out the validation in a customer's environment, but it would be much better if there was a solution in the standard functionality (IMHO).

**Comment by bjompen** [comment]
Hello Axel. 
We are aware of this problem,
but unfortunately, right now there is no easy way to change this behaviour except for manually updating the clients scripts.
We are currently looking in to how to structure a new version of the SLM scripts, but it is not done yet.

Also, this problem is not related to the module, but the importscripts that is not published here,
So any future changes for this problem will not be pushed to this repo.
Marking this as closed, and noted in the future plan for the scheduled task scripts.

**Comment by Axel-L** [comment]
Hi Björn,

I thought this is the perfect place and I was wrong :-)

No worries, as long as there is a workaround we always solve it for the customers.
Thank you for your reply,
Axel

**Comment by bjompen** [comment]
No wrong place, it's more a note som if anyone else stumbles on to the problem it might be clearer where the source and sollution is located :)
